version: "3"

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/jobbackend
    build: ./backend
    container_name: backend
    command:
      - ./commands/start_server.sh
    expose:
      - ${WSGI_PORT}
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    image: ${DOCKER_HUB_USERNAME}/jobfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        VUE_APP_BACKEND: ${VUE_APP_BACKEND}
    container_name: frontend
    env_file:
      - .env
    ports:
      - 80:80
    command:
      /bin/sh -c "envsubst < /etc/nginx/conf.d/fastapi.conf.template > 
      /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend

  postgres:
    image: postgres:12
    container_name: postgres
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: { }
