version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8008
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 8080:8080


  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5434:5432
    env_file:
      - ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - 5000:80
    env_file:
      - ./backend/.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  pg_data: { }
  pgadmin_data: { }

