version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    command:
      - ./commands/start_server.sh
    expose:
      - ${WSGI_PORT}
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    expose:
      - 8080

  postgres:
    image: postgres:12
    container_name: postgres
    expose:
      - 5432
    env_file:
      - ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
      image: nginx
      volumes:
        - ./nginx/default-dev.conf:/etc/nginx/conf.d/fastapi.conf.template
      ports:
        - 80:80
        - 443:443
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/fastapi.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      env_file:
        - ./backend/.env
      depends_on:
        - backend

volumes:
  pg_data: { }